### ISSUE TITLE
Elaborar um DIAGRAMA DE IMPLANTAÇÃO (DEPLOYMENT DIAGRAM) da solução.

### ISSUE THREAD

**Issue by tmsasaki** [Jefferson2703/SGE#12]
Dica: procurar por DEPLOYMENT DIAGRAM UML para ver alguns exemplos.

**Comment by tmsasaki** [comment]
Como o diagrama não representa nenhum ambiente específico de implantação, não é necessário mostrar o FIREWALL.

Ajustar as conexões no diagrama: o computador cliente se conecta ao servidor web, mas não se conecta diretamente ao servidor de banco de dados.

**Comment by Jefferson2703** [comment]
Diagrama de implantação atualizado como foi solicitado professor.
