### ISSUE TITLE
Desenvolver e implantar uma aplicação Hello World na plataforma escolhida para o projeto.

### ISSUE THREAD

**Issue by tmsasaki** [Jefferson2703/SGE#5]

**Comment by Jefferson2703** [comment]
http://ec2-13-58-253-128.us-east-2.compute.amazonaws.com/testeSGE/index.php

**Comment by tmsasaki** [comment]
Ok. Verificado. Se quiser, pode desligar a máquina para não consumir créditos da sua conta.
